const RTO_MAP = {
  // ==========================================
  // PUNJAB
  // ==========================================
  "amritsar": { rto: "PB02", state: "Punjab" },
  "bathinda": { rto: "PB03", state: "Punjab" },
  "faridkot": { rto: "PB04", state: "Punjab" },
  "firozpur": { rto: "PB05", state: "Punjab" },
  "gurdaspur": { rto: "PB06", state: "Punjab" },
  "hoshiarpur": { rto: "PB07", state: "Punjab" },
  "jalandhar": { rto: "PB08", state: "Punjab" },
  "kapurthala": { rto: "PB09", state: "Punjab" },
  "ludhiana": { rto: "PB10", state: "Punjab" },
  "patiala": { rto: "PB11", state: "Punjab" },
  "ropar": { rto: "PB12", state: "Punjab" },
  "rupnagar": { rto: "PB12", state: "Punjab" },
  "sangrur": { rto: "PB13", state: "Punjab" },
  "barnala": { rto: "PB19", state: "Punjab" },
  "pathankot": { rto: "PB35", state: "Punjab" },
  "mohali": { rto: "PB65", state: "Punjab" },
  "sas nagar": { rto: "PB65", state: "Punjab" },
  "fatehgarh sahib": { rto: "PB23", state: "Punjab" },
  "moga": { rto: "PB29", state: "Punjab" },
  "mansa": { rto: "PB31", state: "Punjab" },
  "fazilka": { rto: "PB22", state: "Punjab" },
  "tarn taran": { rto: "PB46", state: "Punjab" },

  // ==========================================
  // HARYANA
  // ==========================================
  "ambala": { rto: "HR01", state: "Haryana" },
  "yamunanagar": { rto: "HR02", state: "Haryana" },
  "panchkula": { rto: "HR03", state: "Haryana" },
  "karnal": { rto: "HR05", state: "Haryana" },
  "panipat": { rto: "HR06", state: "Haryana" },
  "kurukshetra": { rto: "HR07", state: "Haryana" },
  "kaithal": { rto: "HR08", state: "Haryana" },
  "sonipat": { rto: "HR10", state: "Haryana" },
  "rohtak": { rto: "HR12", state: "Haryana" },
  "jhajjar": { rto: "HR14", state: "Haryana" },
  "jind": { rto: "HR31", state: "Haryana" },
  "hisar": { rto: "HR20", state: "Haryana" },
  "bhiwani": { rto: "HR16", state: "Haryana" },
  "sirsa": { rto: "HR24", state: "Haryana" },
  "fatehabad": { rto: "HR22", state: "Haryana" },
  "gurugram": { rto: "HR26", state: "Haryana" },
  "gurgaon": { rto: "HR26", state: "Haryana" },
  "faridabad": { rto: "HR38", state: "Haryana" },
  "rewari": { rto: "HR36", state: "Haryana" },
  "narnaul": { rto: "HR35", state: "Haryana" },
  "mahendragarh": { rto: "HR35", state: "Haryana" },
  "palwal": { rto: "HR50", state: "Haryana" },
  "mewat": { rto: "HR74", state: "Haryana" },
  "nuh": { rto: "HR74", state: "Haryana" },

  // ==========================================
  // HIMACHAL PRADESH
  // ==========================================
  "shimla": { rto: "HP03", state: "Himachal Pradesh" },
  "dharamshala": { rto: "HP39", state: "Himachal Pradesh" },
  "kangra": { rto: "HP40", state: "Himachal Pradesh" },
  "mandi": { rto: "HP33", state: "Himachal Pradesh" },
  "kullu": { rto: "HP34", state: "Himachal Pradesh" },
  "solan": { rto: "HP14", state: "Himachal Pradesh" },
  "sirmour": { rto: "HP18", state: "Himachal Pradesh" },
  "nahan": { rto: "HP18", state: "Himachal Pradesh" },
  "una": { rto: "HP72", state: "Himachal Pradesh" },
  "hamirpur": { rto: "HP22", state: "Himachal Pradesh" },
  "bilaspur": { rto: "HP24", state: "Himachal Pradesh" },
  "chamba": { rto: "HP48", state: "Himachal Pradesh" },
  "kinnaur": { rto: "HP25", state: "Himachal Pradesh" },
  "lahaul and spiti": { rto: "HP42", state: "Himachal Pradesh" },

  // ==========================================
  // JAMMU & KASHMIR
  // ==========================================
  "srinagar": { rto: "JK01", state: "Jammu and Kashmir" },
  "jammu": { rto: "JK02", state: "Jammu and Kashmir" },
  "anantnag": { rto: "JK03", state: "Jammu and Kashmir" },
  "budgam": { rto: "JK04", state: "Jammu and Kashmir" },
  "baramulla": { rto: "JK05", state: "Jammu and Kashmir" },
  "doda": { rto: "JK06", state: "Jammu and Kashmir" },
  "kathua": { rto: "JK08", state: "Jammu and Kashmir" },
  "kupwara": { rto: "JK09", state: "Jammu and Kashmir" },
  "poonch": { rto: "JK12", state: "Jammu and Kashmir" },
  "pulwama": { rto: "JK13", state: "Jammu and Kashmir" },
  "rajouri": { rto: "JK11", state: "Jammu and Kashmir" },
  "ramban": { rto: "JK19", state: "Jammu and Kashmir" },
  "reasi": { rto: "JK20", state: "Jammu and Kashmir" },
  "samba": { rto: "JK21", state: "Jammu and Kashmir" },
  "shopian": { rto: "JK22", state: "Jammu and Kashmir" },
  "udhampur": { rto: "JK14", state: "Jammu and Kashmir" },

  // ==========================================
  // RAJASTHAN
  // ==========================================
  "jaipur": { rto: "RJ14", state: "Rajasthan" },
  "jodhpur": { rto: "RJ19", state: "Rajasthan" },
  "kota": { rto: "RJ20", state: "Rajasthan" },
  "udaipur": { rto: "RJ27", state: "Rajasthan" },
  "ajmer": { rto: "RJ01", state: "Rajasthan" },
  "alwar": { rto: "RJ02", state: "Rajasthan" },
  "banswara": { rto: "RJ03", state: "Rajasthan" },
  "barmer": { rto: "RJ04", state: "Rajasthan" },
  "bharatpur": { rto: "RJ05", state: "Rajasthan" },
  "bhilwara": { rto: "RJ06", state: "Rajasthan" },
  "bikaner": { rto: "RJ07", state: "Rajasthan" },
  "bundi": { rto: "RJ08", state: "Rajasthan" },
  "chittorgarh": { rto: "RJ09", state: "Rajasthan" },
  "churu": { rto: "RJ10", state: "Rajasthan" },
  "dholpur": { rto: "RJ11", state: "Rajasthan" },
  "dungarpur": { rto: "RJ12", state: "Rajasthan" },
  "ganganagar": { rto: "RJ13", state: "Rajasthan" },
  "jaisalmer": { rto: "RJ15", state: "Rajasthan" },
  "jalore": { rto: "RJ16", state: "Rajasthan" },
  "jhalawar": { rto: "RJ17", state: "Rajasthan" },
  "jhunjhunu": { rto: "RJ18", state: "Rajasthan" },
  "nagaur": { rto: "RJ21", state: "Rajasthan" },
  "pali": { rto: "RJ22", state: "Rajasthan" },
  "sikar": { rto: "RJ23", state: "Rajasthan" },
  "sirohi": { rto: "RJ24", state: "Rajasthan" },
  "tonk": { rto: "RJ26", state: "Rajasthan" },
  "hanumangarh": { rto: "RJ31", state: "Rajasthan" },

  // ==========================================
  // UTTAR PRADESH
  // ==========================================
  "agra": { rto: "UP80", state: "Uttar Pradesh" },
  "aligarh": { rto: "UP81", state: "Uttar Pradesh" },
  "prayagraj": { rto: "UP70", state: "Uttar Pradesh" },
  "allahabad": { rto: "UP70", state: "Uttar Pradesh" },
  "azamgarh": { rto: "UP50", state: "Uttar Pradesh" },
  "bareilly": { rto: "UP25", state: "Uttar Pradesh" },
  "bijnor": { rto: "UP20", state: "Uttar Pradesh" },
  "bulandshahr": { rto: "UP13", state: "Uttar Pradesh" },
  "deoria": { rto: "UP52", state: "Uttar Pradesh" },
  "etawah": { rto: "UP75", state: "Uttar Pradesh" },
  "ayodhya": { rto: "UP42", state: "Uttar Pradesh" },
  "faizabad": { rto: "UP42", state: "Uttar Pradesh" },
  "ghaziabad": { rto: "UP14", state: "Uttar Pradesh" },
  "gorakhpur": { rto: "UP53", state: "Uttar Pradesh" },
  "jhansi": { rto: "UP93", state: "Uttar Pradesh" },
  "kanpur": { rto: "UP78", state: "Uttar Pradesh" },
  "lucknow": { rto: "UP32", state: "Uttar Pradesh" },
  "mathura": { rto: "UP85", state: "Uttar Pradesh" },
  "meerut": { rto: "UP15", state: "Uttar Pradesh" },
  "mirzapur": { rto: "UP63", state: "Uttar Pradesh" },
  "moradabad": { rto: "UP21", state: "Uttar Pradesh" },
  "muzaffarnagar": { rto: "UP12", state: "Uttar Pradesh" },
  "noida": { rto: "UP16", state: "Uttar Pradesh" },
  "gautam buddha nagar": { rto: "UP16", state: "Uttar Pradesh" },
  "rae bareli": { rto: "UP33", state: "Uttar Pradesh" },
  "saharanpur": { rto: "UP11", state: "Uttar Pradesh" },
  "shahjahanpur": { rto: "UP27", state: "Uttar Pradesh" },
  "sultanpur": { rto: "UP44", state: "Uttar Pradesh" },
  "varanasi": { rto: "UP65", state: "Uttar Pradesh" },
  "jaunpur": { rto: "UP62", state: "Uttar Pradesh" },
  "ballia": { rto: "UP60", state: "Uttar Pradesh" },
  "mau": { rto: "UP54", state: "Uttar Pradesh" },
  "basti": { rto: "UP51", state: "Uttar Pradesh" },


  // ==========================================
  // MADHYA PRADESH
  // ==========================================
  "bhopal": { rto: "MP04", state: "Madhya Pradesh" },
  "indore": { rto: "MP09", state: "Madhya Pradesh" },
  "gwalior": { rto: "MP07", state: "Madhya Pradesh" },
  "jabalpur": { rto: "MP20", state: "Madhya Pradesh" },
  "ujjain": { rto: "MP13", state: "Madhya Pradesh" },
  "sagar": { rto: "MP15", state: "Madhya Pradesh" },
  "satna": { rto: "MP19", state: "Madhya Pradesh" },
  "rewa": { rto: "MP17", state: "Madhya Pradesh" },
  "ratlam": { rto: "MP43", state: "Madhya Pradesh" },
  "dewas": { rto: "MP41", state: "Madhya Pradesh" },
  "murwara": { rto: "MP21", state: "Madhya Pradesh" },
  "katni": { rto: "MP21", state: "Madhya Pradesh" },
  "singrauli": { rto: "MP66", state: "Madhya Pradesh" },
  "burhanpur": { rto: "MP68", state: "Madhya Pradesh" },
  "khandwa": { rto: "MP12", state: "Madhya Pradesh" },
  "east nimar": { rto: "MP12", state: "Madhya Pradesh" },
  "bhind": { rto: "MP30", state: "Madhya Pradesh" },
  "chhindwara": { rto: "MP28", state: "Madhya Pradesh" },
  "guna": { rto: "MP08", state: "Madhya Pradesh" },
  "shivpuri": { rto: "MP33", state: "Madhya Pradesh" },
  "vidisha": { rto: "MP40", state: "Madhya Pradesh" },
  "chhatarpur": { rto: "MP16", state: "Madhya Pradesh" },
  "damoh": { rto: "MP34", state: "Madhya Pradesh" },
  "mandsaur": { rto: "MP14", state: "Madhya Pradesh" },
  "khargone": { rto: "MP10", state: "Madhya Pradesh" },
  "west nimar": { rto: "MP10", state: "Madhya Pradesh" },
  "neemuch": { rto: "MP44", state: "Madhya Pradesh" },
  "pithampur": { rto: "MP11", state: "Madhya Pradesh" },
  "dhar": { rto: "MP11", state: "Madhya Pradesh" },
  "hoshangabad": { rto: "MP05", state: "Madhya Pradesh" },
  "narmadapuram": { rto: "MP05", state: "Madhya Pradesh" },
  "itarsi": { rto: "MP05", state: "Madhya Pradesh" },
  "sehore": { rto: "MP37", state: "Madhya Pradesh" },
  "betul": { rto: "MP48", state: "Madhya Pradesh" },
  "seoni": { rto: "MP22", state: "Madhya Pradesh" },
  "datia": { rto: "MP32", state: "Madhya Pradesh" },
  "nagda": { rto: "MP13", state: "Madhya Pradesh" },
  "dindori": { rto: "MP52", state: "Madhya Pradesh" },
  "shahdol": { rto: "MP18", state: "Madhya Pradesh" },
  "sidhi": { rto: "MP53", state: "Madhya Pradesh" },
  "balaghat": { rto: "MP50", state: "Madhya Pradesh" },
  "ashoknagar": { rto: "MP67", state: "Madhya Pradesh" },
  "tikamgarh": { rto: "MP36", state: "Madhya Pradesh" }
  
};


module.exports = { RTO_MAP };